### ISSUE TITLE
twitter.config file doesnt exist in project

### ISSUE THREAD

**Issue by aysuays** [cafeasp/TwitterAPI#1]
` <appSettings file="C:\MyAppSettings\Twitter.config">`

can you please share twitter.config file ?

**Comment by cafeasp** [comment]
Below is example. You do need to change the values. 
https://gist.github.com/cafeasp/d328f866bb517090bdb215a66b30c182

**Comment by cafeasp** [comment]
Here is the example.
<?xml version="1.0" encoding="utf-8" ?>
<appSettings>
   <add key="AppId" value="your_app_id" />
   <add key="AppSecret" value="your_app_secret" />
   <add key="AppScope" value="read_orders,write_orders" />
</appSettings>
